#install-services.yaml

---
  - hosts: Utility
    become: true
    tasks: 
      - name: Installing Apache
        yum:  
          name=httpd  
          state=present
      - name: Start Apache
        service: name=httpd state=started enabled=yes

  - hosts: master:Edge
    become: true
    tasks: 
      - name: Installing services
        yum: 
          name:
            - httpd
            - php
          state:  present
      - name: Start Apache
        service: name=httpd state=started enabled=yes